version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
      MONGO_INITDB_DATABASE: bagni_X_booking_system_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - internal
    command: sh -c "/wait && node server.js"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "brinternal"
