version: '3.1'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_DATABASE=bagni_X_booking_system_db
    expose:
      - 27017
    # deploy:
    #  restart_policy:
    #    condition: on-failure
    volumes:
      - ./storage-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # — mongo-data:/data/db # saves locally db

  # for production: recommended to add a container for mongodb handling, ex. mongo-express

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    # deploy:
    #  restart_policy:
    #    condition: on-failure
    command: sh -c "/wait && node server.js"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
