version: '3'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
      # - IMAGE_VERSION=non_serve
    image: server
    #    image: vic/debian.iptables.ifconfig
    environment:
    #- MIAVAR=non_serve__solo_come_esempio
    ports:
      - 3000:3000
    networks:
      - internal
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
      # - IMAGE_VERSION=non_serve
    image: database
    environment:
    #- MIAVAR=non_serve3__solo_come_esempio
    ports:
      - 27017-27019:27017-27019
    networks:
      - internal
#    volumes:
#      - mydata:/data

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "brinternal"
#      com.docker.network.enable_ipv6: "false"
#volumes:
#  mydata:

