openapi: 3.0.1
info:
  title: BagniXBookingSystemApi
  description: Progetto per l'esame di ASW di Maldini, Gorini e Angelini.
  version: "0.1"
servers:
  - url: http://localhost:3000
paths:
  /api/customers/{user-id}:
    get:
      summary: It returns the user-id description
      description: User data
      parameters:
        - name: user_id  (in query used id)
          in: path
          description: User identificator
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized
    put: --> used also for logical delete
      summary: It allows the user to modify some data about hisself
      description: User data
      parameters:
        - name: user_id  (in query used id)
          in: path
          description: User identificator
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/customers/:
    post:
      summary: It returns the user-id description
      description: User data
      parameters:
        - name: registered
          in: query
          description: Specifies whether the passed user has a real profile in Firebase Authentication.
          required: true
          style: simple
          explode: false
          schema:
            type: boolean

      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/feed/:
    get:
      summary: It returns the of the page-id page
      description: Feed
      parameters:
        - name: page_id
            in: query
            description: Page identificator. If speficied, only bookings relative to the page are returned.
            required: false
            style: form
            explode: true
            schema:
              type: integer

        - name: page_size
            in: query
            description: It specifies that the returned booking are only of the number given.
            required: false
            style: form
            explode: true
            schema:
              type: integer
      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/bookings/:
    get:
      summary: It returns some bookings, related optionally to a user. If page size is not specified, the first 10 are returned.
      description: Booking
      parameters:
        - name: user_id
          in: query
          description: User identificator. If the parameter is present, bookings from the specified user are returned.
          required: false
          style: simple
          explode: false
          schema:
            type: string

        - name: page_id
            in: query
            description: Page identificator. If speficied, only bookings relative to the page are returned.
            required: false
            style: form
            explode: true
            schema:
              type: integer

        - name: page_size
            in: query
            description: It specifies that the returned booking are only of the number given.
            required: false
            style: form
            explode: true
            schema:
              type: integer

      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/bookings/{booking-id}/:
    get:
      summary: It returns the booking with id booking_id
      description: Booking
      parameters:
        - name: booking_id
          in: path
          description: Booking identificator
          required: true
          style: simple
          explode: false
          schema:
            type: string

      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized
    put:
      summary: It allows the user to modify the booking
      description: Booking
      parameters:
        - name: booking_id
          in: path
          description: Booking identificator
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized
    delete:
      summary: It deletes a reservation
      description: Modifica-aggiunta prenotazione
      parameters:
        - name: booking_id
          in: path
          description: Booking identificator
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/new-booking/availability/:
    get:
      summary: It returns all the available places in the period, also available selectable services, rank linked to every umbrella
      description: New booking
      parameters:
        - name: from
            in: query
            description: Start booking date
            required: true
            style: form
            explode: true
            schema:
              type: date

        - name: to
          in: query
          description: End booking date
          required: true
          style: form
          explode: true
          schema:
            type: date

      responses:
        "200":
          description: OK
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/new-booking/checkout/:
    post:
      summary: All fields of a booking, i.e. umbrella id, services, price, ecc.
      description: It allows the user to book a site
      responses:
        "200":
          description: OK, all fields of the confirmed booking, included the id
        "400":
          description: FAIL
        "403":
          description: Unauthorized

  /api/home/:
    get:

  /api/catalog/umbrellas/:
    get:
    post:

  /api/catalog/umbrellas/{umbrella_id}:
    get:
    put:

  /api/catalog/ranks/:
    get:
    post:

  /api/catalog/ranks/:id:
    put:

  /api/catalog/sales/:
    get:
      parameters:
        - name: rank_id
          in: query
          description: Rank to refer for the sale
          required: false
          style: form
          explode: true
          schema:
            type: string

        - name: page_id
          in: query
          description: Page identificator. If speficied, only sales relative to the page are returned.
          required: false
          style: form
          explode: true
          schema:
            type: integer

        - name: page_size
          in: query
          description: It specifies that the returned salews are only of the number given.
          required: false
          style: form
          explode: true
          schema:
             type: integer
    post:

    /api/catalog/sales/{sale_id}:
      get:
        parameters:
          - name: sale_id
            in: path
            description: Id to refer for the sale
            required: false
            style: form
            explode: true
            schema:
              type: string
      put:
        parameters:
          - name: sale_id
            in: path
            description: Id to refer for the sale
            required: false
            style: form
            explode: true
            schema:
              type: string

  /api/catalog/services/:
    get:
      parameters:
        - name: page_id
          in: query
          description: Page identificator. If speficied, only sales relative to the page are returned.
          required: false
          style: form
          explode: true
          schema:
            type: integer

        - name: page_size
          in: query
          description: It specifies that the returned salews are only of the number given.
          required: false
          style: form
          explode: true
          schema:
            type: integer
    post:

    /api/catalog/services/:id:
      get:
        parameters:
          - name: service_id
            in: path
            description: Service id
            required: true
            style: form
            explode: true
            schema:
              type: integer

    /api/stats/:
      description: robe

components: {}
