# The aim of this action is to control the correctness of the build only.
# It builds the mongodb image, compiles the Angular client and tries to fetch
# dependencies.
name: Docker Compose CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
